apiVersion: apps/v1
kind: Deployment
metadata:
  name: landlord-app-deployment
  namespace: landlord-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landlord-app
  template:
    metadata:
      labels:
        app: landlord-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: landlord-app
          image: munimdevops/landlord-management-api:94
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/landlord_management_tz
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true   # Now safe!
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 500Mi  # Optional limit
---
apiVersion: v1
kind: Service
metadata:
  name: landlord-app-service
  namespace: landlord-management
spec:
  selector:
    app: landlord-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort