apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: landlord-management
type: Opaque
stringData:
  jwt-secret: "YmFzZTY0LWVuY29kZWQtc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXRlc3RpbmctcHJvamVjdA=="